language: swift
osx_image: xcode7.3
script:  
  - xctool -project BikeyProvider.xcodeproj -scheme BikeyProvider -sdk iphonesimulator
  - xctool test -project BikeyProvider.xcodeproj -scheme BikeyProvider -sdk iphonesimulator
   