language: objective-c
osx_image: xcode7.3
script:  
  - xctool -project SPBBikeProvider.xcodeproj -scheme SPBBikeProvider -sdk iphonesimulator
  - xctool test -project SPBBikeProvider.xcodeproj -scheme SPBBikeProvider -sdk iphonesimulator
   